In [8]:
import pandas as pd
from verma_net_radiation_sensitivity.verma_net_radiation_sensitivity import process_verma_net_radiation_table

In [9]:
verma_net_radiation_inputs_df = pd.read_csv("calval_final_50_FLiES_outputs.csv")
verma_net_radiation_inputs_df

,Unnamed: 0.1,tower,lat,lon,orbit,scene,tile,time_UTC,date_UTC,doy,...,ST_C,elevation_km,Ra,UV,VIS,NIR,VISdiff,NIRdiff,VISdir,NIRdir
0,0,US-Ha2,42.5393,-72.1779,9254,9,18TYN,2020-02-22 00:00:00,2020-02-22,53,...,0.89,0.058,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,US-Ha2,42.5393,-72.1779,10150,9,18TYN,2020-04-20 00:00:00,2020-04-20,111,...,35.39,0.058,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,US-Ha2,42.5393,-72.1779,10352,9,18TYN,2020-05-03 00:00:00,2020-05-03,124,...,13.17,0.058,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,US-Ha2,42.5393,-72.1779,10684,7,18TYN,2020-05-24 00:00:00,2020-05-24,145,...,15.61,0.058,35.081859,0.592462,3.964455,3.539386,3.627162,3.519072,0.337294,0.020315
4,4,US-Ha2,42.5393,-72.1779,11069,8,18TYN,2020-06-18 00:00:00,2020-06-18,170,...,28.03,0.058,79.432091,1.386834,9.353725,8.820494,7.418505,8.696527,1.935220,0.123967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,247,US-xUK,39.0404,-95.1921,11909,6,15SUD,2020-08-11 00:00:00,2020-08-11,224,...,26.43,0.529,307.048509,2.746542,17.376796,12.682295,14.372975,12.682295,3.003822,0.000000
248,248,US-xUK,39.0404,-95.1921,16668,8,15SUD,2021-06-14 00:00:00,2021-06-14,165,...,22.77,0.529,403.617014,13.811569,125.868830,142.625977,32.456092,15.308895,93.412739,127.317082
249,249,US-xUK,39.0404,-95.1921,16810,8,15SUD,2021-06-23 00:00:00,2021-06-23,174,...,17.11,0.529,406.616093,14.346120,119.526664,125.834733,38.645010,27.577193,80.881654,98.257540
250,250,US-xUK,39.0404,-95.1921,16810,8,15SUD,2021-06-23 00:00:00,2021-06-23,174,...,30.71,0.529,406.616093,14.346120,119.526664,125.834733,38.645010,27.577193,80.881654,98.257540
251,251,US-xUN,46.2339,-89.5373,12274,4,15TYM,2020-09-04 00:00:00,2020-09-04,248,...,6.47,0.548,116.319866,0.594074,3.113654,2.262866,2.846623,2.261136,0.267030,0.001731

In [10]:
verma_net_radiation_inputs_df.columns

Index(['Unnamed: 0.1', 'tower', 'lat', 'lon', 'orbit', 'scene', 'tile',
       'time_UTC', 'date_UTC', 'doy', 'time_solar', 'AOT', 'COT', 'vapor_gccm',
       'ozone_cm', 'SZA', 'KG', 'Unnamed: 0', 'lat_Y', 'lon_Y', 'orbit_Y',
       'scene_Y', 'tile_Y', 'time_UTC_Y', 'time_solar_Y', 'BESSinst', 'ESI',
       'ESIdaily', 'ESIdailyUncertainty', 'ETdaily', 'ETdailyUncertainty',
       'ETinstUncertainty', 'EmisWB', 'GPP', 'LST', 'LST_err', 'MOD16inst',
       'NDVI-UQ', 'PET', 'PTJPLSMcanopy', 'PTJPLSMinst', 'PTJPLSMinterception',
       'PTJPLSMsoil', 'RH', 'Rg', 'Rn', 'SM', 'STICcanopy', 'STICinst', 'Ta',
       'WUE', 'albedo-UQ', 'height', 'radiance_1', 'radiance_2', 'radiance_3',
       'radiance_4', 'radiance_5', 'view_zenith', 'year', 'Ta_C', 'ST_K',
       'NDVI', 'albedo', 'ST_C', 'elevation_km', 'Ra', 'UV', 'VIS', 'NIR',
       'VISdiff', 'NIRdiff', 'VISdir', 'NIRdir'],
      dtype='object')

In [11]:
net_radiation_outputs = process_verma_net_radiation_table(verma_net_radiation_inputs_df)
net_radiation_outputs

,Unnamed: 0.1,tower,lat,lon,orbit,scene,tile,time_UTC,date_UTC,doy,...,UV,VIS,NIR,VISdiff,NIRdiff,VISdir,NIRdir,SWout,LWin,LWout
0,0,US-Ha2,42.5393,-72.1779,9254,9,18TYN,2020-02-22 00:00:00,2020-02-22,53,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,223.482510,310.837408
1,1,US-Ha2,42.5393,-72.1779,10150,9,18TYN,2020-04-20 00:00:00,2020-04-20,111,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,249.470817,483.042043
2,2,US-Ha2,42.5393,-72.1779,10352,9,18TYN,2020-05-03 00:00:00,2020-05-03,124,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,293.358154,368.124775
3,3,US-Ha2,42.5393,-72.1779,10684,7,18TYN,2020-05-24 00:00:00,2020-05-24,145,...,0.592462,3.964455,3.539386,3.627162,3.519072,0.337294,0.020315,0.662989,NaN,385.565499
4,4,US-Ha2,42.5393,-72.1779,11069,8,18TYN,2020-06-18 00:00:00,2020-06-18,170,...,1.386834,9.353725,8.820494,7.418505,8.696527,1.935220,0.123967,2.254700,380.029433,454.438012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,247,US-xUK,39.0404,-95.1921,11909,6,15SUD,2020-08-11 00:00:00,2020-08-11,224,...,2.746542,17.376796,12.682295,14.372975,12.682295,3.003822,0.000000,5.351180,414.848071,439.377199
248,248,US-xUK,39.0404,-95.1921,16668,8,15SUD,2021-06-14 00:00:00,2021-06-14,165,...,13.811569,125.868830,142.625977,32.456092,15.308895,93.412739,127.317082,27.991697,NaN,405.251251
249,249,US-xUK,39.0404,-95.1921,16810,8,15SUD,2021-06-23 00:00:00,2021-06-23,174,...,14.346120,119.526664,125.834733,38.645010,27.577193,80.881654,98.257540,28.021802,NaN,388.004691
250,250,US-xUK,39.0404,-95.1921,16810,8,15SUD,2021-06-23 00:00:00,2021-06-23,174,...,14.346120,119.526664,125.834733,38.645010,27.577193,80.881654,98.257540,28.021802,400.532814,463.095778
251,251,US-xUN,46.2339,-89.5373,12274,4,15TYM,2020-09-04 00:00:00,2020-09-04,248,...,0.594074,3.113654,2.262866,2.846623,2.261136,0.267030,0.001731,0.797800,NaN,339.018157

In [12]:
net_radiation_outputs.to_csv("calval_final_50_verma_net_radiation_outputs.csv", index=False)

In [13]:
net_radiation_outputs.ST_C

0       0.89
1      35.39
2      13.17
3      15.61
4      28.03
       ...
247    26.43
248    22.77
249    17.11
250    30.71
251     6.47
Name: ST_C, Length: 252, dtype: float64